### ISSUE TITLE
Unable to visualize using binary

### ISSUE THREAD

**Issue by ghost** [hdc-arizona/traveler-gantt#2]
![1](https://user-images.githubusercontent.com/68087711/98848916-466f4380-2407-11eb-8148-7ee6f578bc61.png)

After trying the `./Traveler -e -t ./APEX.otf2` command I am unable to visualize the trace file in the browser. The browser just shows the directory where the binary is present and clicking any icon just downloads that file. 

I am attaching a photo of the visualization, thank you.

**Comment by kisaacs** [comment]
Hello! 

I would ask you a bunch of questions (e.g., operating systems, how the trace was obtained... that zero second read time looks suspicious) to help try to debug the problem, but the easiest thing to do might be to try the more active version of Traveler: https://github.com/hdc-arizona/traveler-integrated

It has the Gantt chart visualization as well as many others and is typically more scalable.

Thanks for the heads up. I should add the above to the README.

**Comment by ghost** [comment]
I am using Ubuntu 18.04 and the trace was generated from an hpx (built with APEX) example. I was able to visualize the same exact trace on vampir though.

**Comment by kisaacs** [comment]
Ah I recall this error. I think we fixed it in the Traveler-Integrated version: https://github.com/hdc-arizona/traveler-integrated

**Comment by ghost** [comment]
Thank you, that worked.
